### ISSUE TITLE
Weird artifact in the restored result

### ISSUE THREAD

**Issue by chhkang** [zhaominyiz/C3-STISR#4]
I made the test with your code and get the same performance as you reported in Readme. That's cool, however, when I visualize the reconstruct result with visualize option in your code, I can find it has some unusual visual artifact.

[restored picture](url) is as followed, and as you can see, restoration picture shows decreased visual quality and background color is getting a little different. 
![lr_sr_hr_0006_810ujioz_1880uazo3_188041903_18301903_18301903](https://user-images.githubusercontent.com/32183422/190345086-fc2593f0-0829-4cd3-a4a7-cfb5fa1796d1.jpg)

Performance is exactly same as you reported, so I ask you whether this artifact a usual one.

Best

**Comment by zhaominyiz** [comment]
Yes, the visual result may have some changes since recognition & linguistical clues are not designed for improving fidelity. To achieve a better fidelity performance, you may utilize visual clue and pixel losses to obtain a variant.

Best

**Comment by zhaominyiz** [comment]
Following are some experimental results in my supplementary materials, I think it will be useful for you to balance recognition performance and fidelity:
For fidelity performance, we can drop the text-specific losses. As for recognition performance, we can apply the iterative super-resolution proposed in [Ma et al., 2021]. We apply these two tricks and develop two variants. The experimental results can be checked in Tab. 3. As shown in Tab. 3, our variants achieve satisfied fidelity or recognition performance, respectively.
![image](https://user-images.githubusercontent.com/43022408/190348071-1d59b18b-222a-4643-8d07-6144dc008216.png)
