### ISSUE TITLE
About Pretrained BCN_correct_model.pt

### ISSUE THREAD

**Issue by csguoh** [zhaominyiz/C3-STISR#9]
Hi, author! 
When I want to load the pretrained model as you have advised in https://github.com/zhaominyiz/C3-STISR/issues/7#issuecomment-1321144434, however, I met problem in  the line   `params = torch.load('ckpt/BCN_correct_model.pt')` . I couldn't find this pretrained model `BCN_correct_model.pt` in your release. I wonder if it is convenient for you to share this? Thank you !

**Comment by zhaominyiz** [comment]
Hi,
Related parameters are provided in https://github.com/zhaominyiz/C3-STISR/releases/tag/C3-STISR-RecLing
Best!
